### ISSUE TITLE
Error message: "ERROR|de.sgollmer.solvismax.model.Solvis - Data received without timestamp, channel: 09. Current time used

### ISSUE THREAD

**Issue by Fl77777** [GollmerSt/SolvisSmartHomeServer#13]
Hi when using the following command in Homeassistant:

action: mqtt.publish
data:
  topic: SolvisSmartHomeServer/Homeassistant/mySolvis/C05:WassertemperaturSoll/cmnd
  payload: "46.0"

I get the following error message:

"ERROR|de.sgollmer.solvismax.model.Solvis - Data received without timestamp, channel: C09. Current time used."

and the value C05:WassertemperaturSoll/cmnd is not changed on the display of Solvis control 2.

Any tips?

**Comment by schrej-zz** [comment]
Just a guess: send it as integer 46 instead of 46.0
But the error message is irritating.

**Comment by Fl77777** [comment]
Writing it as an integer or a float doesn't seem to make a difference. Despite the error message the mqqt.publish command changes the C05:WassertemperaturSoll value properly.
