### ISSUE TITLE
Anlagenstatus wird nicht angelernt

### ISSUE THREAD

**Issue by schrej-zz** [GollmerSt/SolvisSmartHomeServer#2]
Hallo,
bei mir kommt das Anlernen nicht über den <Anlagenstatus WW> hinweg.
Danach:
```
14:44:59,868|LEARN|Screen grafic <Anlagenstatus WW Max> learned.
14:45:03,833|LEARN|Screen <Anlagenstatus> not learned. White fields of the scree
ns does not fit to the current screen.
```
Ich habe noch einen externen Brenner. Kann das die Ursache sein.
![Solvis_Heizkreis](https://user-images.githubusercontent.com/4101445/92243227-6e02d680-eec1-11ea-9a96-2307ed55c854.jpg)

**Comment by GollmerSt** [comment]
Hallo,

ja, das ist die Ursache. Ich untersuche in dem Bild folgende zwei Bereiche (grau markiert):

![Anlagenstatus HK](https://github.com/GollmerSt/SolvisSmartHomeServer/raw/master/docu/images/Anlagenstatus-Bereiche%202020-09-05.png)

Der linke Bereich (mit dem Brenner) darf nicht leer sein, der rechte muss leer sein.

Da muss ich noch ein anderes Kriterium finden, um die 3 Bildschirme voneinander zu unterscheiden.

Ich wollte heute noch ein Pre-Release freigeben. Da wird es voraussichtlich berücksichtigt sein.

Viele Grüße
   Stefan

**Comment by GollmerSt** [comment]
Fixed with [V01.02.03-rc6](https://github.com/GollmerSt/SolvisSmartHomeServer/releases/tag/v01.02.03-rc6--mqtt-beta--3-heating-circuits-beta)
