### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by wullimann** [GollmerSt/SolvisSmartHomeServer#3]
Hallo GollmerSt,

danke für das tolle Projekt, die Solvis mehr oder weniger IOT-fähig zu bekommen. Ich habe allerdings das Problem, daß der Server mit einem Fehler aussteigt, wenn ich den MQTT-Teil in die` base.xml `Datei einfüge.

`java -jar SolvisSmartHomeServer.jar 
de.sgollmer.solvismax.error.XmlError: 
	at de.sgollmer.solvismax.Main.main(Main.java:79)`

Die `base.xml`, die im git repository ist enthält den mqtt-Abschnitt allerdings nicht. Ich habe daher den Abschnitt eingefügt, den Du im Wiki publiziert hast.

Gruß,
Martin

**Comment by GollmerSt** [comment]
Hallo wulliman,
leider sehe ich Dein issue erst jetzt, irgendwie habe ich das in meinem Mail-Eingang übersehen.
Die Fehlermeldung ist leider nicht sehr Aussage-kräftig, da muss ich mal sehen, woran es liegt.

Hier meine eigene MQTT-Passage der base.xml:

`	<tns:Mqtt enable="true" brokerUrl="192.168.1.75" port="1883"
		subscribeQoS="1" publishQoS="1" idPrefix="SolvisSmartHomeServer"
		topicPrefix="SolvisSmartHomeServer" />
`

Könntest Du vielleicht den MQTT-Teil der base.xml hier einfügen.

Vielel Grüße
    Stefan

**Comment by GollmerSt** [comment]
Hallo wullimann,

ich habe jetzt mal gezielt in meinen base.xml einen Fehler reingebracht. Bei mir sieht es dann so aus:

> $ java -jar SolvisSmartHomeServer.jar
> INFO: Line: 39, Column: 3 Error: The content of elements must consist of well-formed character data or markup.
> Reading of base.xml not successfull
> de.sgollmer.xmllibrary.XmlException:
>         at de.sgollmer.solvismax.Main.execute(Main.java:146)
>         at de.sgollmer.solvismax.Main.main(Main.java:394)
> base.xml couldn't be read.
> 

`(Main.java:79)` irritiert mich bei Dir sehr, das wäre noch der Part, der die Command-Line interpretiert. Das passt dann aber wieder mit dem XmlError nicht zusammen.

In welcher Umgebung versuchst Du den Server zu starten (OS, Java-Version)?

Lief der Server ohne den Mqtt-Teil schon oder gab es dort ebenfalls Probleme?

Was mich etwas wundert, die base.xml des Paketes hat eigentlich den MQTT-Teil drin. Nur steht aktuell das Attribute "enable" auf "false". Da müsste man nur auf true setzen und die mqttBrokerUrl eintragen.

Im Paket selber ist die unter "SolvisSmartHomeServer/rsc/de/sgollmer/solvismax/data/base.xml" zu finden.

**Comment by wullimann** [comment]
Ich versuche es in Docker zum Laufen zu bekommen. Die Umgebung ist Ubuntu 18.04 mit `openjdk-8-jre`. 

Mit dem MQTT-Abschnitt läuft es weiterhin nicht. Wenn ich ihn herausnehme, kann ich die Anlage anlernen:

```
java -jar SolvisSmartHomeServer.jar --server-learn
19:09:18,376|LEARN|***********************************************************************
19:09:18,377|LEARN|                     A T T E N T I O N
19:09:18,377|LEARN|
19:09:18,377|LEARN|The file <control.xml> was manually changed. It's renamed to
19:09:18,378|LEARN|<control.xml.1>.The new one of the new server version is used!
19:09:18,378|LEARN|***********************************************************************
19:09:18,419|LEARN|Learning started.
19:09:30,551|LEARN|Screen grafic <Home> learned.
19:09:34,080|LEARN|Screen grafic <Solar> learned.
19:09:38,178|LEARN|Configuration mask: 0x100000b
19:09:45,096|LEARN|Screen grafic <Button_HK1> learned.
19:09:53,172|LEARN|Screen grafic <Nachttemperatur> learned.
19:09:53,203|LEARN|Screen grafic <NachttemperaturNotSelected> learned.
19:09:56,695|LEARN|Screen grafic <NachttemperaturSelected> learned.
19:10:03,339|LEARN|Screen grafic <Warmwasser> learned.
19:10:44,494|LEARN|Screen grafic <Button_HK2> learned.
19:10:52,563|LEARN|Screen grafic <Tagestemperatur> learned.
19:10:52,594|LEARN|Screen grafic <TagestemperaturNotSelected> l
```

Andererseits ist das Verhalten des Programms anders als im Wiki: Das Anlernen läuft nicht automatisch bei Bedarf, sondern er fordert mich explizit dazu auf. Weiterhin wundert mich, daß Du im Wiki von einer 1.2.1 schreibst. Im Git log ist die letzte getaggte Version die v01.02.08:

```
commit 3b98dff75d9fd7543fcb99ed7e70dddf164ecab0 (tag: v01.02.08--3-heating-circuits-beta)
Author: Stefan Gollmer <Stefan.Gollmer57@gmail.com>
Date:   Fri Dec 25 12:06:49 2020 +0100
``` 
Das jar-file `SolvisSmartHomeServer.jar`  ist auch schon 6 Monate alt im `master-branch`. Kann es daran liegen, daß ich die falsche Version habe? 

Gruß, Martin

**Comment by GollmerSt** [comment]
Hallo Martin,

> Das jar-file SolvisSmartHomeServer.jar ist auch schon 6 Monate alt im master-branch. Kann es daran liegen, daß ich die falsche Version habe?

Das dürfte die Jar-Version noch sein, die ich vor GitHub immer ins SVN eingecheckt hatte um zur Not die alte Version Bit-genau sicher zu erzeugen.

Ich müsste das aus GitHub rauslöschen, nicht dass es wieder Missverständnisse gibt. Daher passte vermutlich auch nicht die Zeilennummer zum aktuellen Code. Seitdem, ist einiges auf der MQTT-Seite auch geändert worden, auch der Mqtt-Tag der base.xml wurde geändert, was beim Programmstart immer geprüft wird.

Die aktuellen Jar-Files findest Du immer unter Releases, die checke ich seit GitHub nicht mehr ein.

Die Relases findest Du hier:

[https://github.com/GollmerSt/SolvisSmartHomeServer/releases](url)

Da müsste dann das Learning auch automatisch erfolgen. Das wird auch erneut erfolgen, da in der Zwischenzeit auch das Steuerfile, in dem die ganzen Beschreibungen der Solvis-Grafik drinsteckt mehrfach geändert wurde.

Viele Grüße und viel Erfolg
      Stefan

**Comment by wullimann** [comment]
So, nun funktioniert es. Habe nun aber ein neues Problem. Mache dazu ein neuen Issue auf.

Danke aber soweit!
