### ISSUE TITLE
Erkennung des Anlagenstatus scheitert

### ISSUE THREAD

**Issue by wullimann** [GollmerSt/SolvisSmartHomeServer#4]
Hallo Stefan,

beim Anlernen der Bedienelemente, steigt der Server immer beim Anlagenstatus auf der Seite der Heizung aus:

```
20:09:41,789|LEARN|Screen grafic <Heizkreise> learned.
20:09:45,790|LEARN|Screen grafic <Heizkreis> learned.
20:10:20,466|LEARN|Screen grafic <Schornsteinfeger> learned.
20:10:28,015|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:10:35,550|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:10:43,069|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:10:50,575|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:10:58,159|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:05,699|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:13,280|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:20,826|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:28,352|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:35,874|LEARN|Screen <Anlagenstatus> not learned. White fields of the screens does not fit to the current screen.
20:11:43,380|LEARN|Screen <Anlagenstatus> not learned. Selected screen is not part of ScreenSequence. Learning screen will be tried again
20:11:46,901|ERROR|de.sgollmer.solvismax.model.objects.screen.Screen - Learning of screen <Anlagenstatus> not possible. Learning terminated.
20:11:46,902|ERROR|de.sgollmer.solvismax.Main - Exception on reading configuration or learning files occured, cause:: de.sgollmer.solvismax.error.LearningTerminationException: Learning of screen <Anlagenstatus> not possible. Learning terminated.
	at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:488)
	at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:462)
	at de.sgollmer.solvismax.model.objects.screen.Screen.learnScreens(Screen.java:393)
	at de.sgollmer.solvismax.model.Solvis.learning(Solvis.java:452)
	at de.sgollmer.solvismax.model.Instances.learn(Instances.java:90)
	at de.sgollmer.solvismax.Main.execute(Main.java:255)
	at de.sgollmer.solvismax.Main.main(Main.java:394)
de.sgollmer.solvismax.error.LearningTerminationException: Learning of screen <Anlagenstatus> not possible. Learning terminated.
	at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:488)
	at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:462)
	at de.sgollmer.solvismax.model.objects.screen.Screen.learnScreens(Screen.java:393)
	at de.sgollmer.solvismax.model.Solvis.learning(Solvis.java:452)
	at de.sgollmer.solvismax.model.Instances.learn(Instances.java:90)
	at de.sgollmer.solvismax.Main.execute(Main.java:255)
	at de.sgollmer.solvismax.Main.main(Main.java:394)
```

Die Meldung lautet ja `White fields of the screens does not fit to the current screen.` Da Winter ist und der Brenner läuft, dachte ich, daß es an der kleinen Brenner-Animation liegt. Daher habe ich alle Heizkreise deaktiviert. Lediglich die Pumpensymbole blinken noch. Das Erkennen der Grafiken scheitert dennoch.

![display](https://user-images.githubusercontent.com/76973379/104506540-d38c6f80-55e5-11eb-9d2d-b5ec336f2356.png)

Bei der Erstellung dieser Grafik lief der Brenner wieder.

Liegt es evtl. an der Version meiner Solvis Software?

Gruß,
Martin

**Comment by GollmerSt** [comment]
Hallo Martin,

soweit ich es erkenne, unterscheidet sich die Grafiken etwas von den mir bisher bekannten.

Das Kesselsymbol ist niedriger und oben stärker abgerundet. Dadurch kommt die Umrandung des Kessels in den Bereich rein, den ich als weiß erwarte. Dadurch kann er die Anlagenmodus nicht  unterscheiden und bricht nach mehrfachen Versuchen ab.

Was für eine Anlage besitzt Du? Welche Firmware?

Die Firmware-Version findest Du unter Sonstig./weiter/System Informationen unten links.

Könntest Du die restlichen Screens von den 3 Anlagenstatus auch noch hier ablegen? Dann kann ich die Felder vermutlich so anpassen, dass es für alle (mir bekannten) Versionen passt. Sollte das nicht gehen, dann muss ich es von der Anlage abhängig machen.

Ich hoffe es gibt nicht noch weitere Überraschungen mit weiteren Grafiken. Das werden wir dann sehen.

Viele Grüße
   Stefan

**Comment by GollmerSt** [comment]
Hallo Martin,

ich hatte mir die Screens der Analgenstatus doch nochmal angesehen und SolvisBen und SolvisMax7 scheinen doch sehr ähnlich zu sein.
Ich habe die XML-Steuerdatei entsprechend angepasst und einen neuen Unit-Type definiert. Eine Prerelease-Version steht Dir nun unter folgendem Pfad zur Verfügung:

[https://github.com/GollmerSt/SolvisSmartHomeServer/releases/tag/v01.02.09-rc1](url)

In der base.xml müsstest Du unter `/BaseData/Units/Unit@type` den Wert `SolvisMax7` eintragen.

Leider konnte ich es mangels Harware noch nicht testen.

Könntest Du dann wenn Du es mal hast laufen lassen (auch erfolglos), mal den Inhalt des Ordners
`<writablePathLinux>/SolvisServerData/LearnedImages` packen und hier als Anhang ablegen?

Dann hätte ich direkt sämtliche Screens der SolvisMax7, welche der Server auswertet und kann sie  bei zukünftigen Änderungen berücksichtigen.

Vielen Dank
     Stefan

**Comment by wullimann** [comment]
Hallo Stefan

vielen Dank für das Update. Das Einlernen hat geklappt! Anbei der gepackte Inhalt von `LearnedImages` 

[LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/5851921/LearnedImages.zip)
 
Ist es beim MQTT Broker auch möglich, sich mit Benutzername und Passwort anzumelden?

Gruß,
Martin

**Comment by GollmerSt** [comment]
Hallo Martin,

oh ja, habe ich leider nicht in der `base.xml ` drin.

Es gibt dazu zwei Attribute im Mqtt-Tag:

userName="_user name_" passwordCrypt="_password crypted mit dem gleichen Verfahren wie Mail und Solvis-Passwort_"

Damit sollte es gehen, habe ich aber leider noch nicht getestet.

Viele Grüße
    Stefan

**Comment by wullimann** [comment]
Ich habe einfach einen MQTT Listener ohne Authentifizierung zusätzlich eingerichtet - und es funktioniert! Ich werde es mal mit Name/Passwort bei Gelegenheit testen. Vielen Dank soweit!
