### ISSUE TITLE
MQTT subscriptions

### ISSUE THREAD

**Issue by wullimann** [GollmerSt/SolvisSmartHomeServer#5]
Hi,

für mich ist noch nicht ganz ersichtlich, wie ich Werte/Einstellungen der Anlage via MQTT ändere. Der Server ist mit `Feature id="OnlyMeasurements" value="false"` konfiguriert. Ich möchte nun den Anlagenmodus_HK1 auf *Standby* ändern. An welches Topic muß ich dazu genau welchen Wert senden? Alles was ich bisher versucht habe, führt zu keiner Änderung.

Gruß, Martin

**Comment by GollmerSt** [comment]
Hallo Martin,

hatte leider Deinen Anfrage übersehen.

Es gibt für die Kanäle, welche modifiziert werden können immer zwei unterschiedliche Topics.

Der eine Topic liefert die eingestellten Werte, mit dem anderen Topic kann man die Werte verändern.

Bei mir ist im base.xml folgende Werte, darauf basieren dann die weiter unten angeführten Topic-Namen:

<tns:Mqtt  ....   topicPrefix="SolvisSmartHomeServer" ....
<tns:Unit id="mySolvis" ...

Das Topic für die Daten lautet bei mir:

`SolvisSmartHomeServer/mySolvis/C06:Anlagenmodus_HK1/data`

Das Topic, um den Anlagen-Modus zu modifizieren lautet bei mir:

`SolvisSmartHomeServer/IoBroker/mySolvis/C06:Anlagenmodus_HK1/cmnd`

"IoBroker" ist nur der Name des Client, welcher den Befehl absetzt und ist zwingend! Ich vermute, an der Stelle hapert es bei Dir momentan. Das ist eine etwas ungewöhnliche Sache und erstmal auch nicht intuitiv.

Es gibt einige Befehle, bei denen sich der SolvisSmartHomeServer den Client merken muss. Der Client selber ist aus der reinen MQTT-Spezifikation nicht ermittelbar. Daher muss der Client-Name im Topic  stehen. Der Name ist beliebig, wenn man unterschiedliche Clients verwendet, müssen sie jedoch eindeutig sein. Diesen Vorschlag hatte ich in einem Forum gefunden.

Bei dem Anlagen-Modus wird der Client in Wirklichkeit ignoriert. Der Server reagiert auf folgenden Topic mit * als Wildcard:

`SolvisSmartHomeServer/*/mySolvis/C06:Anlagenmodus_HK1/cmnd`


Viele Grüße
   Stefan
