### ISSUE TITLE
Get channels of screen <Zaehlfunktion> not successfull

### ISSUE THREAD

**Issue by florix121** [GollmerSt/SolvisSmartHomeServer#6]
Hallo,

Ich betreibe eine Solvis-Anlage bestehend aus einem SolvisMax 7 und einem Solvis Lino. Vor Kurzem habe ich die aktuelle Version des SolvisSmartHomeServers installiert.
Nach dem Start des SolvisSmartHomeServer Service erscheint jedoch folgende Fehlermeldung:
`|ERROR|de.sgollmer.solvismax.model.CommandControl - Get channels of screen <Zaehlfunktion> not successfull. Aborted.`
Alle weiteren Funktionen laufen, soweit ich das überblicken kann, problemlos.

Da ich selbst keine Lösung für das Problem gefunden habe, wollte ich fragen ob, ein solches Verhalten bekannt ist oder ob ich bei der Konfiguration einen Fehler gemacht habe?

Die Zählfunktion meiner Anlage besteht aus zwei Seiten mit den Elementen: Laufzeit Solarpumpe 1, Laufzeit Solarpumpe 2, Wärmemenge Solar, Wärmemenge WW, Starts Brenner und Laufzeit Brenner (gesamt):
![zaehl1](https://user-images.githubusercontent.com/82665587/115046566-e447cc80-9ed7-11eb-853b-5691e970028a.jpg)
![zaehl2](https://user-images.githubusercontent.com/82665587/115046568-e4e06300-9ed7-11eb-9af0-0c4c36e81018.jpg)

Mit freundlichen Grüßen
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

oha, wieder ein andere Solvis-Firmware mit einer leicht varierten Grafik. Bei den bisher mir bekannten Anlagen gibt es hier nur
einen Bildschirm und zwar:

![Zählfunktion Gas](https://raw.githubusercontent.com/GollmerSt/SolvisSmartHomeServer/master/docu/images/Hierarchie/6%20Sonstig%202/Z%C3%A4hlfunktion%20Gas.png)

Dort gibt es nur ein Feld mit der Laufzeit der Solarpumpe, die Laufzeiten beider Pumpen sind durch / getrennt. Das kann daher bei Dir nicht funktionieren.

Soweit ich es überblicke, bist Du der erste, der mein Tool für die SolvisMax 7 verwendet.

Ich werde das bei der nächsten Version berücksichtigen. Soweit ich es erkenne sind die erforderlichen Mechanismen im Programm vorhanden. Es ist nur eine Ergänzung einer Steuerdatei notwendig.

Testen müsstest Du es dann.

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo Stefan,

vielen Dank schon mal für deine schnelle Antwort.
Werde die neue Version gerne testen!

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo,
ich habe gerade ein Pre-release freigegeben, darin ist u.a. die Anpassung für diese Firmware enthalten.

Die Configuration-Mask in der base.xml muss für diese Firmwareauf den Wert 0x0110 gesetzt werden. Evtl. sind dort noch - je nach Anlage -weitere Bits zu setzen. Die Werte dafür stehen in der base.xml.

Mit welchem SmartHome-System hast Du vor den SolvisSmartHomeServer zu nutzen?

Könntest Du auch in gepackter Form die Scrreen-Grafiken hier ablegen, welche im "LearnedImages"-Ordner während des Learning gespeichert werden? Dann kann ich die Probleme nachvollziehen und bei künftigen Änderungen besser testen. Danke.

Noch eine Frage, benötigst Du die Werte "Wärmemenge WW" und "Wärmemenge Solar" auch auf der SmartHome-Seite? Die könnte ich noch mit auslesen. Wobei "Wärmemenge Solar" eigentlich dem Wert "SE.Solarertrag_kWh" entsprechen müsste. Der wird über die XML-Schnittstelle ohne die "GUI-Verrenkung" schon ermittelt. Oder ist es doch etwas anderes?

Viel Erfolg mit der neuen Version.

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,
Ich habe die neue Programmversion installiert und die base.xml soweit angepasst. Jetzt bekomme ich jedoch beim Anlernen folgenden Fehler:

```
ERROR de.sgollmer.solvismax.model.objects.screen.Screen - Learning of screen <Anlagenstatus> not possible. Learning terminated.
ERROR de.sgollmer.solvismax.Main - Exception on reading configuration or learning files occured, cause:: de.sgollmer.solvismax.error.LearningTe$
        at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:488)
        at de.sgollmer.solvismax.model.objects.screen.Screen.learn(Screen.java:462)
        at de.sgollmer.solvismax.model.objects.screen.Screen.learnScreens(Screen.java:393)
        at de.sgollmer.solvismax.model.Solvis.learning(Solvis.java:492)
        at de.sgollmer.solvismax.model.Instances.learn(Instances.java:91)
        at de.sgollmer.solvismax.Main.execute(Main.java:256)
        at de.sgollmer.solvismax.Main.main(Main.java:395)
```

Als SmartHome-System verwende ich Node-Red, welches den SolvisSmartHomeServer über die MQTT Schnittstelle ausließt. Das funktioniert bisher auch soweit ganz gut.

Die "Wärmemenge Solar" entspricht dem "SE.Solarertrag_kWh" Wert. Wenn es keine großen Umstände macht wäre es schön, die "Wärmemenge WW" auch auslesen zu können.

[LeardnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6331104/LeardnedImages.zip)

Des Weiteren ist mir aufgefallen, dass die Anschlüsse der Geräte an den SolvisMax von meinen abweicht:
A01 hier Pumpe Solar und bei mir Pumpe Zirkulation
A05 hier Pumpe_Warmwasserzirkulation und bei mir Pumpe HK 3
A06 und A07 bei mir HK3 Mischer auf und zu
S07 hier Solardruck bei mir eine zweite Solar-VL Messung
S15 bei mir Kaltwasser (jedoch nur ein festgelegter statischer Wert, kein Sensor)
AIn3 bei mir Solardruck
AOut0 bei mir Temperaturvorgabe für SolvisLino 3
AOut1 bei mir PWM Solarpumpe 1
AOut2 bei mir PWM Solarpumpe 2 
AOut3 bei mir PWM WW-Pumpe 
AOut5 bei mir PWM Ladepumpe

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

habe anhand der Hardcopies des Anlagenstatus noch ein paar Koordinaten angepasst. Ich hoffe es klappt nun besser. Hier der Link zu der Version:

https://github.com/GollmerSt/SolvisSmartHomeServer/releases/tag/v01.02.11-rc2

Die Sache mit den Kanalzuordnungen muss ich mir später ansehen. Da hat sich bei der SolvisMax 7 gegenüber der 6 wohl einiges geändert. Aber erstmal muss das Learning durchkommen.

Vielel Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,
ich habe die neue Version getestet und bekomme jetzt beim Anlernen einen anderen Fehler. Hier der Log ab Serverstart:
```
INFO de.sgollmer.solvismax.Main - Server started, Version 01.02.11-rc2, 3 heating circuits beta, SolvisMax 7 beta
INFO Learning started.
INFO Screen grafic <Home1> learned.
INFO Screen grafic <Home2> learned.
INFO Screen grafic <Home3> learned.
INFO Screen grafic <Solar> learned.
INFO Configuration mask: 0x4000119
INFO Screen grafic <Nachttemperatur> learned.
INFO Screen grafic <NachttemperaturNotSelected> learned.
INFO Screen grafic <NachttemperaturSelected> learned.
INFO Screen grafic <Warmwasser> learned.
INFO Screen grafic <Sonstiges-1> learned.
INFO Screen grafic <Sonstiges> learned.
INFO Screen grafic <Heizkreise> learned.
INFO Screen grafic <Heizkreis> learned.
INFO Screen grafic <Schornsteinfeger> learned.
INFO Screen grafic <Anlagenstatus-HK Ben/Max7> learned.
INFO Screen grafic <Anlagenstatus-Solar Ben/Max7> learned.
INFO Screen grafic <Anlagenstatus-WW Ben/Max7> learned.
INFO Screen grafic <Sonstiges-2> learned.
INFO Screen grafic <ZaehlfunktionRef> learned.
INFO Screen grafic <Sonstiges_Nutzerauswahl> learned.
INFO Screen grafic <Nutzerauswahl> learned.
INFO Screen grafic <Sonstiges-3> learned.
INFO Screen grafic <Uhrzeit/Datum> learned.
INFO Screen grafic <Zeiteinstellung> learned.
INFO Screen grafic <Zirkulation> learned.
INFO Screen grafic <Tagestemperatur> learned.
INFO Screen grafic <TagestemperaturNotSelected> learned.
INFO Screen grafic <TagestemperaturSelected> learned.
INFO Screen grafic <Zeiteinstellung_YYYY> learned.
INFO Screen grafic <Zeiteinstellung_MM> learned.
INFO Learning of clock not successfull, try it again.
INFO Screen grafic <Zeiteinstellung_DD> learned.
INFO Screen grafic <Zeiteinstellung_hh> learned.
INFO Screen grafic <Zeiteinstellung_min> learned.
INFO Screen grafic <WWPumpeAus> learned.
INFO Screen grafic <WWPumpeAn> learned.
INFO Screen grafic <WWPumpeAuto> learned.
INFO de.sgollmer.solvismax.model.objects.control.Control - Channel <C04.WarmwasserPumpe> is set to auto>.
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Screen grafic <ModeStandby> learned.
INFO Screen grafic <ModeTimer> learned.
INFO Learning of <Timer> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Screen grafic <ModeStandby> learned.
INFO Screen grafic <ModeTimer> learned.
INFO Learning of <Timer> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Screen grafic <ModeStandby> learned.
INFO Learning of <Standby> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Learning of <Nacht> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Learning of <Nacht> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Learning of <Nacht> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Screen grafic <ModeStandby> learned.
INFO Screen grafic <ModeTimer> learned.
INFO Learning of <Timer> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Learning of <Tag> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Screen grafic <ModeStandby> learned.
INFO Learning of <Standby> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
INFO Screen grafic <ModeTag> learned.
INFO Screen grafic <ModeNacht> learned.
INFO Learning of <Nacht> not successfull, will be retried
INFO Learning of <C06.Anlagenmodus_HK1> not successfull, will be retried
ERROR de.sgollmer.solvismax.model.objects.control.Control - Learning of <C06.Anlagenmodus_HK1> not possible, rejected. Check the control.xml!
ERROR de.sgollmer.solvismax.Main - Exception on reading configuration or learning files occured, cause:: de.sgollmer.solvismax.error.LearningEx$
        at de.sgollmer.solvismax.model.objects.control.Control.learn(Control.java:312)
        at de.sgollmer.solvismax.model.objects.ChannelDescription.learn(ChannelDescription.java:213)
        at de.sgollmer.solvismax.model.objects.AllChannelDescriptions.learn(AllChannelDescriptions.java:133)
        at de.sgollmer.solvismax.model.Solvis.learning(Solvis.java:494)
        at de.sgollmer.solvismax.model.Instances.learn(Instances.java:91)
        at de.sgollmer.solvismax.Main.execute(Main.java:256)
        at de.sgollmer.solvismax.Main.main(Main.java:395)
```

Und hier die LearnedImages:
[LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6331527/LearnedImages.zip)

Werden noch weiter Informationen gebraucht?

Vielen Dank für die Mühe
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

so wie es aussieht, scheint das Umschalten des Mode bei Dir länger zu dauern. Insgesamt sieht es schon recht gut aus, wobei die Erkennung des Anlagenstatus WW nicht ganz optimal ist, aber es trotzdem funktionieren dürfte. Da muss ich mir etwas besseres einfallen lassen, ist aktuell doch sehr Firmware-abhängig.

Habe die ModeChange-Zeit von 3 auf 3,5s erhöht. Sollte hoffentlich reichen.

Die neue Version ist unter folgendem Link zu finden:

[https://github.com/GollmerSt/SolvisSmartHomeServer/releases/tag/v01.02.11-rc3](url)

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,
das Einlernen funktioniert jetzt (fast) problemlos (Anlernen von Standby und 06.Anlagenmodus_HK1 schlägt mehrfach fehl und muss wiederholt werden).
Die Werte der Zählfunktion korrekt ausgelesen.

Falls gewollt kann ich gerne noch weitere Funktionen testen und Informationen zu meinem System liefern.

Vielen Dank
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

dauert der Mode-Wechsel wirklich so lang  bei Dir (Druck auf den Button bis das Symbol sich ändert) oder liegt ein andere Grund vor? Andere Möglichkeit wäre, dass die Länge des Tastendrucks nicht ausreicht (400ms). Seltsam, dass das nur bei der Mode-Umschaltung Probleme bereitet. Erkennt man das mit der trägen Reaktion auch schon bei der Bedienung im Browser?

Morgen werde ich mir die Sache mit der unterschiedlichen Kanalbelegung ansehen. Ich denke, es wäre besser, wenn das auch in der base.xml definiert/modifiziert werden kann. Dann ist das flexibler. Es gibt schon bei der SolvisMax 6 recht viel unterschiedliche Konstellationen (Pellet, Wärmepumpe etc.). Wenn dann noch andere Belegungen bei der SolvisMax 7 hinzu kommt, wäre das in der base.xml besser aufgghoben.

Viele Grüße
   Stefan

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

ich habe den Mode-Wechsel mal im Web-Interface getestet. Die Reaktionszeit unterscheidet sich teils extrem und willkürlich. Es kann also sein, dass es daran liegt, ich kann es jedoch nicht mit Sicherheit sagen. Ich denke die Länge des Tastendrucks ist ausreichend. Ich habe das Verhalten beim Anlernen der Modi über das Webinterface beobachtet und es sah für mich so aus, als würde der SolvisMax jeden Tastendruck des SolvisSmartHomeServer auch durchführt. Kann ich das noch irgendwie anders testen?

Bei der Kanalbelegung kann ich zumindest für den SolvisMax 7 sagen, dass es bei Solvis direkt dazu eigentlich eine sehr gute Dokumentation gibt ([Anlagenschema SolvisMax](https://solvis-files.s3.eu-central-1.amazonaws.com/downloads-fk/solvismax7/plattform/27350_ALS_MAX-7.pdf)). Wie es bei den anderen Versionen aussieht kann ich leider nicht sagen.

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

ich habe mir inzwischen mir das Anlagenschema angesehen. Daraus erkennt man, dass die SolvisMax 7 noch mehr Kanäle besitzt bzw. diese anders benannt werden. Das sind z.B. die Kanäle W, SP1, SP2 und O-1. Ich habe mir mal das Anlagenschema angesehen, was im SolvisMax7-Fall verwendet wird. Danach scheint SP1 AOut1 zugeordnet zu sein und W ist AOut5 zugeordnet, letzteres wird aktuell wird vom Server noch nicht ausgeklesen, das war wohl in einer späteren SolvisRemote-FW reingekommen. Das werde ich ergänzen.

Kannst Du ermitteln, auf welchem Kanal die Solarpumpe 2 angezeigt wird (müsste einer von den AOut sein)? Die wird ja immer etwas zeitversetzt mit der Solarpumpe 1 gestartete.

Ich werde es so ändern, dass die eindeutigen Kanäle durch den Anlagentyp schon richtig benannt werden. Nur die nicht eindeutigen, wie z.B. S16, A6, A7 können dann der base.xml noch der Konstellation entsprechend benannt werden. Dann benötige ich nicht mehr so viele Bits dafür in der Config-Mask.

Die "Wärmemenge WW" werde ich dann auch noch erfassen.

Zum Mode-Wechsel: Ich werde auch die Warte-Zeit für den Mode-Wechsel in der base.xml konfiguurierbar machen. Dann kannst Du den Wert noch etwas variieren. Wenn das Learning geklappt hat, sollte es immer funktionieren, auch wenn die zeit zu knapp ist, da jede GUI-Aktion immer auch im GUI verififiziert wird. Er würde dann den Befehl nochmal wiederholen und nochmals im GUI die Änderung verifizieren. Das musste ich machen, weil auch bei meiner Anlage manchmal ein Button-Druck von der Anlage nicht ausgeführt wird.

Noch eins:
Du hast in der base.xml den Admin-Mode eingeschaltet. Ich weiß nicht, ob Du das wirklich benötigst. Dadurch geht er auch in den Installateur-Modus (Eingabe 0064) und liest dort auch ein paar weitere Sachen aus. Meist ist das nicht notwendig.
Wenn Du aber dort oder überhaupt noch mehr benötigst (Auslesen/Setzen), einfach sagen. Erweiterungen sind leicht möglich. Da muss nur die control.xml-Datei erweitert werden.

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

Abgesehen von den S## und A## Ein- und Ausgängen habe ich für mein System folgende Zuordnung gefunden:

O-1 = AOut0 = Temperaturvorgabe SolvisLino 3 (Standard Umrechnung: 3,0V = 30°C; 8,0V = 80°C; zu sehen in INSTALLATEUR-MENÜ>HEINZUNG>MODULATION)
SP1 = AOut1 = PWM Solarpumpe 1 in %
SP2 = AOut2 = PWM Solarpumpe 2 in %
LP = AOut3 = PWM Ladepumpe in %
W = AOut5 = PWM WW-Pumpe in %

I-3 = AIn3 = Solardruck (Standard Umrechnung: 0,5V = 0,0bar; 3,5V = 6,5bar; zu sehen in INSTALLATEUR-MENÜ>MELDUNG>SOLARDRUCK 2/3)

An I-1 und I-2 ist an meiner Anlage nichts angeschlossen. Ich würde aber davon ausgehen, dass I-1 = AIn1 und I-2 = AIn2.

Admin-Mode habe ich eigentlich nicht eingschaltet (`<tns:Feature id="Admin" value="false" />`), da ich mich im Installateur-Menü noch nicht wirklich umgeschaut habe. Werde dies demnächst aber noch machen und hier nocheinmal darüber berichten.

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

Danke für die Info. Die werde ich nun  nutzen.

Vielel Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

Ich habe mich gerade mal durch das Service Menü geklickt und da ist mir aufgefallen, dass es noch zwei weitere digitale Eingänge DI-1 und DI-2 gibt. Ob und an was diese angeschlossen sind habe ich jedoch noch nicht herausgefunden.

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

in den Skitze der Netzbaugruppe der SolvisMax7 habe ich die Eingänge nicht gefunden. Es gibt dort noch die Eingänge ST1 und ST2. Ich bin mir nicht sicher, ob das die sind. Soweit ich es erkenne, scheint ST für "Störung" zu stehen. Wäre das möglich?

Im Anlagenschema des Solvis-Browser-Oberfläche werden die leider nicht angezeigt. Daher kenne ich deren Position im XML-String nicht. Das müsste man dann gezielt ermittel. Aber ich denke nicht, dass es nötig ist.

Denn den Störungszustand erkennt der Server über das GUI selber (Störungsmeldung wird eingeblendet bzw. im Hauptscreen ist nicht mehr die Uhr eingeblendet sondern ein Störungssysmbol). Der SolvisStatus in den Zustand Error, optional einen Mail mit dem Screenshot versendet und der Hauptscreen wird angefahren. Durch die Beobachtung des Hauptscreens (Fehlerbutton) wird erkannt, wann der Fehler verschwindet. Auf diese Weise bleibt die Störungsauswertung selber  in den "Händen" der Solvis-Anlage. Man bekommt von Fehlern aber auch dann etwas mit, auch wenn man nicht vor Ort ist.

Ich bin an der Änderung/Erweiterung noch dran. Ich denke einen neuen Pre-release werde ich nächste Woche freigeben.

Viele Grüße
   Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,

kurzer Zwischenstand:

Ich habe doch eine etwas aufwändigere Lösung nun implementiert. Der einfache Weg wie oben beschrieben war leider nicht so zu wirklich sinnvoll. Ich habe jetzt im Server die Anlagekonfigurationsmöglichkeiten laut den Anlagenschema-Dokumentationen für die SolvisMax 6 und SolvisMax 7 definiert. Abgefallen ist da nun auch eine Kanaldefinitionausgabe, wo man die ganzen Kanalbelegungen in Form einer csv-Ausgabe erhält.

Ich habe jetzt die neue Version auf meiner Anlage laufen, muss aber nochmal die Konfigurationen durchprüfen und die Dokumentation aktualisieren. Mit einer neuen Version wird es daher erst im Laufe der nächsten Woche werden.

Viel Grüße
    Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,
ich habe jetzt einen neuen release-Kandidaten erstellt.
Die Bitmaske ist jetzt mehr oder weniger weggefallen.
Für Deinen Anlage solltest Du die Attribute im base.xml wie folgt setzen:

type := SolvisMax7
mainHeating := Extern
heatingCircuits := 1

Zusätzlich müsstest Du noch unter dem Tag Extensions den Tag Extension mit der id "Zaehlfunktion2Screens" ergänzen.

Dann sollten die Solar-Pumpen und auch die anderen Kanäle richtig zugeordnet werden. Unter C29 und C30 solltest Du dann auch der Solarertrag und die WW-Wärmemenge ausgelesen werden.

Die Dokumentation habe ich aktualisiert.

Viele Grüße und viel Erfolg
   Stefan

**Comment by florix121** [comment]
Hallo,

Ich habe die neue Version mal installiert und die base.xml Datei passend angepasst. Bei Einlernen bekomme ich jedoch folgenden wieder Fehler:

`ERROR de.sgollmer.solvismax.model.command.CommandControl - Get channels of screen <Zaehlfunktion> not successfull. Aborted.`

Vermutlich aus diesem Grund, befinden sich auch C29 und C30 nicht in der SolvisChannels.csv und werden nicht über MQTT übermittelt.

Hier noch die angelernten Bilder: [LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6487789/LearnedImages.zip)

Des Weitern habe ich in der base.xml noch folgende Einstellungen vorgenommen:

```
<tns:RegEx>.*HK2.*</tns:RegEx>
<tns:RegEx>.*HK3.*</tns:RegEx>
<tns:RegEx>.*Raumfuehler.*</tns:RegEx>
```

Diese Kanäle werden jedoch trotzdem erfasst. Hat sich an dieser Konfiguration auch etwas geändert?

Vielen Dank
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

bist Du sicher, dass die Extensions bei Dir so aussehen:

`			<tns:Extensions>
				<tns:Extension id="Zaehlfunktion2Screens"/>
			</tns:Extensions>` 

Feststoff (Kamin) und Soar Ost West hast Du ja nicht, daher sollte nur Zaehlfunktion2Screens dort nicht auskommentiert sein.

Kann st Du das nochmal kontrollieren?

Viele Grüße
  Stefan

**Comment by florix121** [comment]
Hallo,

Ich habe werder Feststoff noch Solar Ost West. Hier der passende Abschnitt der base.xml:

```
<tns:Extensions>
  <!-- <tns:Extension id="Festbrennstoff" /> -->
  <!-- <tns:Extension id="SolarOstWest"/> -->
  <tns:Extension id="Zaehlfunktion2Screens"/>
</tns:Extensions>
```

Habe die base.xml.new verwendet und angepasst.

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

habe jetzt die Ursache gefunden. Ich habe die XML-Definition (und damit auch den Parser für die Extensions) in zwei verschiedenen XML-Files verwendet, die dann aber für die andere nochmal geändert, ohne die Definition für die base.xml nachzuziehen.

Ich werde trotzdem die base.xml-Definition beibehalten, weil sie aus meiner Sicht doch sinnvoller ist.

Ich weiß nicht, ob ich es heut Abend noch schaffen werde, meine Familie ruft ;). Morgen Vormittag wird's auf jeden Fall werden.

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

vielen Dank für deine Mühen! Die Familie hat natürlich Vorrang!!

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

hab den Fehler erkannt und gefixt. Habe einen RC2 erstellt.

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

funktioniert jetzte!

Vielen Dank
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

Hast Du auch dieZuordnungen und C29 und C30 überprüfen können? Passt das jetzt so?

könntest Du mir evtl. nochmal den Inhalt des Ordners _LearnedImages_ hier ablegen. Dann habe ich die kompletten Bildschirmkopien Deiner SolvisVersion für weitere Test zur Verfügung.

Vielen Dank
   Stefan

**Comment by florix121** [comment]
Hallo,

die Werte sind alle korrekt. Hier noch der LearnedImages Ordner: [LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6488989/LearnedImages.zip)

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

Danke für die Images. Das klingt ja gut. Dann werde ich mich an einen offiziellen Release machen, muss aber vorher noch von den anderen Konfigurationen die Kanallisten prüfen. Dazu war ich noch nicht richtig gekommen.

Viele Grüße
   Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,

ich habe gerade in den Images gesehen, dass das Anlernen des Anlagenmodes bei Dir nicht richtig gelaufen ist. Die Wartezeit scheint bei Dir dafür einfach nicht auszureichen. Ich untersuche zwar, dass ich 4 unterschiedliche Grafiken erhalte, aber in Deinem Fall ist es trotzdem nicht richtig gelaufen. Aktuell ist bei Dir nach dem falsch gelaufenen Learning-Vorgang die Zuordnung folgende:

Server   | wirklich
-------- | -------
Timer     | Timer
Standby | Nacht
Nacht    | Tag
Tag       | Standby

Dadurch ist meine Plausibbilitätskontrolle (vier unterschiedliche Grafiken) zwar fehlerfrei, trotzdem ist der Learning-Vorgang schief gelaufen.

Ich muss mir mal überlegen, wie ich das besser löse. Aktuell scheint eine feste Wartezeit nicht das Gelbe vom Ei zu sein. Ich denke, ich werde auf eine Änderung auf dem Bildschirm warten. Dann sollte es sicherer sein. Für diese Änderung werde ich aber etwas Zeit benötigen. Vorläufig werde ich die Zeit für den Anlagenmodewechsel in der base.xml definieren. Dann kannst Du gezielt für Deine Anlage einen recht hohen Wert für den Anlangenmode-Wechsel setzen (z.B. 7s statt aktuell 3.5s).

Aktuell müsstest Du nochmal den Learning-Vorgang wiederholen. Aktuell kann nur der Mode "Timer" richtig laufen, alle anderen Zustandwechsel werden einen Fehler bringen.

Viele Grüße
   Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,

ich habe einen weiteren RC erstellt.

Dabei habe ich die obige Erweiterung eingeführt.

Beim Debuggen dieser neuen Funktion habe ich erkannt, dass das Definitionsfile (control.xml) für Deine Konfiguration doch noch einen Fehler aufwies. Für die Anlagenmodus-Wechsel-Zeit - welche bei Dir Probleme bereitet - stand ein fehlerhafter Verweis. Dadurch zeigte die Zeit-Modifikation von vor ein paar Wochen bei Dir überhaupt keine Wirkung. Die Button-Release-Zeit stand immer auf 2s und das ist bei Dir offenbar zu wenig.

Ich habe das jetzt im neuen Release korrigiert, die Release-Time steht nun auf 3s.

Wenn das noch nicht reicht kannst Du nun in der base.xml in der Sektion _Durations_ die folgende Zeile aktivieren (ist momentan auskommentiert):

`<tns:Duration id="ModeChange" time_ms="3500" />`

und die 3500 noch variieren.

Ich werde morgen noch die Doku mit der Beschreibung der damit möglichen zeitlichen Anpassungen erweitern

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

Ich habe die neue Version installiert und nach meinem Verständnis hat das Anlernen schon ohne die base.xml Konfiguration funktioniert. Hier der LearnedImages Ordner: [LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6489983/LearnedImages.zip)

Grüße
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

ja, jetzt passt es. Also die normalen 3s passen auch bei Dir. Gut, wie ich schon schrieb, werde ich noch grob die anderen Konfigurationen kontrollieren und dann eine offizielle Version rausgeben.

Vielen Dank noch
   Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,

ich habe gerade die offizielle Version freigeben, wäre sicher auch für Dich interssant. In dem letzten RC waren noch ein paar Bugs und kleiner Fehler in den Konfigurationen gab es noch.

Viele Grüße
  Stefan

**Comment by florix121** [comment]
Hallo,

ich habe heute mal die neue Version installiert und beim Anlernen des Anlagenmodes gab es scheinbar wieder zu Problemen:

```
|LEARN|Screen grafic <ModeTag> learned.
|LEARN|Screen grafic <ModeNacht> learned.
|LEARN|Learning of <Nacht> not successfull, will be retried
|LEARN|Learning of <C06> not successfull, will be retried
|LEARN|Screen grafic <ModeTag> learned.
|LEARN|Screen grafic <ModeNacht> learned.
|LEARN|Screen grafic <ModeStandby> learned.
|LEARN|Screen grafic <ModeTimer> learned.
|LEARN|Learning of <Timer> not successfull, will be retried
|LEARN|Learning of <C06> not successfull, will be retried
|LEARN|Screen grafic <ModeTag> learned.
|LEARN|Screen grafic <ModeNacht> learned.
|LEARN|Screen grafic <ModeStandby> learned.
|LEARN|Screen grafic <ModeTimer> learned.
```

Hier der LearnedImages Ordner: [LearnedImages.zip](https://github.com/GollmerSt/SolvisSmartHomeServer/files/6522074/LearnedImages.zip)

Ich kann leider nicht beurteilen, ob das final richtig angelernt wurde. Der Rest scheint soweit ich das sehe zu funktionieren.

Vielen Dank
Florian

**Comment by GollmerSt** [comment]
Hallo Florian,

ja, es hatte leichte Probleme gegebn, aber diese wurden auch gleich erkannt und der Anlernvorgang wurde wiederholt und beim 3 mal hatte es richtig geklappt.

Ich denke, dass Du es doch mal mit der Zeile
   <tns:Duration id="ModeChange" time_ms="3500" />
probieren solltest, dann hat wird einen 1/2s länger auf die Reaktion auf die Mode-Buttons gewartet. Bei Dir scheinen die 3s immer noch zu knapp zu sein. Aber wie ghesagt, der Anlernvorgang aht diesmal schon geklappt.

Trotzdem werde ich mir überlegen, ob ich denn Anlernvorgang nicht doch verbessere, dass er auf einen Änderung des Mode-Symbols werst wartet. Akteuell kann der Server einen solche zyklische Vertauschung nicht erklennen, die mit der vorletzten Version bei Dir noch während des Anlernens aufgetreten ist. Kritisch ist das auch nur im Anlernen, später im Betrieb werden "verschluckte" Tastendrücke erkannt und entsprechend wiederholt.

Ich habe es jedenfalls in meinen ToDo-Liste aufgenommen.

Vorher will ich aber noch den "Nachheizen-Button" unterstützen, das ist jetzt aktuell für die interssant, welche mit dem WW-Timer arbeiten.  Ich habe die Funktion bisher nicht gebraucht, weil ich die Timer-Funktion nicht mehr nutze, sondern die WW-Temperatur tageszeitspezifisch über das Smarthomesystem einstelle. Der "Nachheizen-Button"  ist aber etwas anders zu implementieren und daher habe ich das noch nicht in die letzte Version gepackt.

Viele Grüße
  Stefan

**Comment by GollmerSt** [comment]
Hallo Florian,

nur zur Info, in der neuen Version 1.04.00 habe ich das learning so geändert, dass der Server beim Learning untersucht, ob sich das Mode-Symbol geändert hat. Wenn nicht, wird erneut gewartet. So hat die SolvisControl für die Symbolwechsel doppelt so viel Zeit wie bisher. 

Viele Grüße
   Stefan

**Comment by florix121** [comment]
Hallo,

vielen Dank für die Info. Ich werde die neue Version mal auf meinem System ausprobieren.

Viele Grüße
Florian
