### ISSUE TITLE
Can't install via Makefile

### ISSUE THREAD

**Issue by mascheihei** [GollmerSt/SolvisSmartHomeServer#8]
Erstmal vielen Dank für deine Arbeit. Das ist genau das was ich brauche. Leider scheiter ich schon beim ersten Schritt. Wenn ich das makefile aufrufe:

sudo make installSolvis

Scheitere ich schon in der ersten Zeile:

make: *** No rule to make target 'SolvisSmartHomeServer.jar', needed by '/opt/solvis/SolvisSmartHomeServer/SolvisSmartHomeServer.jar'.  Stop.

Irgendeine Idee?

**Comment by GollmerSt** [comment]
Hallo,

das Makefile hatte ich mit der letzten Version angepasst, ich hoffe, dass ich da nichts übersehen habe.

Wenn ich die Meldung richtig interpretiere, versucht er aus welchem Grund auch immer die Datei "SolvisSmartHomeServer.jar" neu zu erstellen. Er scheint die nicht zu finden.

Sie sollte eigentlich in dem Verzeichnis liegen, in dem auch das Makefile zu finden ist. Aus diesem Verzeichnis sollte man auch das Makefile aufrufen. Ich habe gerade in die Zip-Datei des release-Paketes geschaut, da ist sie eigentlich drin.

Du kannst ja auch mal mit "sudo make -d installSolvis" versuchen. Da hat man dann die Aufschlüsselung, wie Make bei der Installation vor geht und wo es evtl. hackt.

Kannst Du den Log dieses Aufrufs hier reinlegen (evtl. auch in gepackter Form)?

Viele Grüße
   Stefan

**Comment by mascheihei** [comment]
Hallo Stefan,

oh ich muss mich entschuldigen. Fehler lag bei mir.
Läuft einwandfrei mit MQTT und ioBroker-Platform. 

Danke!

**Comment by GollmerSt** [comment]
Danke, für die Meldung. Freu mich, dass es bei Dir auch läuft.

Viele Grüße
   Stefan
